src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FactureRepository::class)]
class Facture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $reference = null;

    /**
     * @var Collection<int, Paiement>
     */
    #[ORM\OneToMany(targetEntity: Paiement::class, mappedBy: 'facture', cascade: ['persist', 'remove'])]
    private Collection $paiements;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateFacture = null;

    #[ORM\ManyToOne(inversedBy: 'factures')]
    private ?AnneeScolaire $anneeScolaire = null;

    #[ORM\ManyToOne(inversedBy: 'factures')]
    private ?Ecole $ecole = null;

    public function __construct()
    {
        $this->paiements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return Collection<int, Paiement>
     */
    public function getPaiements(): Collection
    {
        return $this->paiements;
    }

    public function addPaiement(Paiement $paiement): static
    {
        if (!$this->paiements->contains($paiement)) {
            $this->paiements->add($paiement);
            $paiement->setFacture($this);
        }

        return $this;
    }

    public function removePaiement(Paiement $paiement): static
    {
        if ($this->paiements->removeElement($paiement)) {
            // set the owning side to null (unless already changed)
            if ($paiement->getFacture() === $this) {
                $paiement->setFacture(null);
            }
        }

        return $this;
    }

    public function getDateFacture(): ?\DateTimeInterface
    {
        return $this->dateFacture;
    }

    public function setDateFacture(?\DateTimeInterface $dateFacture): static
    {
        $this->dateFacture = $dateFacture;

        return $this;
    }

    public function getAnneeScolaire(): ?AnneeScolaire
    {
        return $this->anneeScolaire;
    }

    public function setAnneeScolaire(?AnneeScolaire $anneeScolaire): static
    {
        $this->anneeScolaire = $anneeScolaire;

        return $this;
    }

    public function getTotalRemis(): int
    {
        $total = 0;

        foreach ($this->paiements as $paiement) {
            // if($paiement->getType() == 'scolarité'){
            $total += $paiement->getMontant();
            //}
        }


        return $total;
    }

    public function getMontantRestant(): int
    {
        $total = 0;

        if (!empty($this->paiements)) {
            foreach ($this->paiements as $paiement) {
                // if($paiement->getType() == 'scolarité'){
                $total += $paiement->getInscription()->getMontantRestant();
                //}
            }
        }

        return $total;
    }

    public function getEcole(): ?Ecole
    {
        return $this->ecole;
    }

    public function setEcole(?Ecole $ecole): static
    {
        $this->ecole = $ecole;

        return $this;
    }
}

src/Entity/Paiement.php
<?php

namespace App\Entity;

use App\Repository\PaiementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PaiementRepository::class)]
class Paiement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $type = null;

    #[Assert\Positive(message : 'Les frais doivent etre supérieur à 0')]
    //#[Assert\LessThanOrEqual($this->inscription->getMontantRestant())]
    #[ORM\Column]
    private ?int $montant = null;

    #[ORM\ManyToOne(inversedBy: 'paiements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Inscription $inscription = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateDeTransaction = null;

    #[ORM\ManyToOne(inversedBy: 'paiements')]
    private ?Facture $facture = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getInscription(): ?Inscription
    {
        return $this->inscription;
    }

    public function setInscription(?Inscription $inscription): static
    {
        $this->inscription = $inscription;

        return $this;
    }

    public function getEleve(): string
    {
        return ($this->getInscription()) ? $this->getInscription()->getEleve()->__toString() : '';
    }

    public function getClasse(): string
    {
        return ($this->getInscription()) ? $this->getInscription()->getClasse()->__toString() : '';

    }

    public function getMontantRestant(): int
    {
        return ($this->getInscription()) ? $this->getInscription()->getMontantRestant() : 0 ;
    }


    public function getTotalRemis(): int
    {
        return  ($this->getInscription()) ? $this->getInscription()->getTotalRemis() : 0;
    }


    public function getTotalAPayer(): int
    {
        return ($this->getInscription()) ? $this->getInscription()->getTotalAPayer() : 0;
    }


    public function getMontantPourPayementUnique(): int
    {
        return ($this->getInscription()) ? $this->getInscription()->getMontantPourRemiseUnique() : 0;
    }


    public function getStatusPaiement(): string
    {
        return ($this->getInscription()) ? strval($this->getTotalRemis()). ' FCFA payés / '.strval($this->getTotalAPayer()) . ' FCFA' : "Pas d'inscription choisi";
    }

    public function __toString()
    {
        return strval('Paiement de ' . $this->getMontant());
    }

    public function getDateDeTransaction(): ?\DateTimeInterface
    {
        return $this->dateDeTransaction;
    }

    public function setDateDeTransaction(?\DateTimeInterface $dateDeTransaction): static
    {
        $this->dateDeTransaction = $dateDeTransaction;

        return $this;
    }

    public function getFacture(): ?Facture
    {
        return $this->facture;
    }

    public function setFacture(?Facture $facture): static
    {
        $this->facture = $facture;

        return $this;
    }
}

templates/components/Encaisseur.html.twig
<div {{ attributes }}>
    {{ form_start(form, {
        attr: {
            'data-action': 'live#action:prevent',
            'data-live-action-param': 'save'
        }
    }) }}


    <div class="form-row bg-dark">
        {{ form_row(form.classe) }}

        {% if form.inscription is defined %}
            {{ form_row(form.inscription) }}
        {% endif %}
    </div>

    <div class="form-group">

        {% if form.status is defined %}
            {{ form_row(form.status) }}
        {% endif %}

    </div>

    <div class="form-group">
        {% if form.montantUnique is defined %}
            {{ form_row(form.montantUnique) }}
        {% endif %}
    </div>

    <div class="form-group">

    </div>

    {% if form.montant is defined %}
        {{ form_row(form.montant) }}
    {% endif %}

    <button>Enregistrer</button>
    {{ form_end(form) }}
</div>

templates/components/EncaisseurGroupe.html.twig
<div {{ attributes }}>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">classe</th>
            <th scope="col">inscrit</th>
            <th scope="col">Montant payé</th>
            <th scope="col">Reste à payer</th>
            <th scope="col">Montant à verser</th>
        </tr>
        </thead>

        <tbody>
        {% for paiement in paiements %}
            {{ component('EncaisseurLigne',{
                dataModel: 'paiement',
                error: _errors.get('paiement'),
            }) }}
        {% endfor %}

        </tbody>
    </table>
    <li> taille paiements {{ paiements|length }}</li>
    <li> taille eleves {{ eleves|length }}</li>


    {{ component('RechercheEleve', {
        dataModel: 'eleves:value',
    }) }}


</div>

templates/components/EncaisseurLigne.html copy.twig
<div {{ attributes }}>
    {{ form_start(form, {
        attr: {
            'data-action': 'live#action:prevent',
            'data-live-action-param': 'save'
        }
    }) }}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">classe</th>
            <th scope="col">inscrit</th>
            <th scope="col">Montant payé</th>
            <th scope="col">Reste à payer</th>
            <th scope="col">Montant à verser</th>
        </tr>
        </thead>
        <tbody>

        <tr>
            <td>{{ form_row(form.classe) }}</td>
            <td>{{ form_row(form.inscription) }}</td>
            <td>{{ form_row(form.montantVerse) }}</td>
            <td>{{ form_row(form.montantRestant) }}</td>
            <td>{{ form_row(form.montant) }}</td>
        </tr>

        </tbody>
    </table>


    {{ form_end(form) }}
</div>

templates/components/EncaisseurLigne.html.twig
<div {{ attributes }}>


    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><input type="number" data-model="paiement.montant"></td>
    </tr>


</div>

templates/components/FactureDeGroupe.html.twig
<div style="background-color: white;" {{ attributes }}>

    <div style="text-align:center">
        <h1> COMPLEXE SCOLAIRE ETOILE DE L’EXCELLENCE </h1>
        <h2> Tél : 90 64 67 72 / 92 21 67 69 <h2>
    </div>

    <div style="text-align:right">
        <h4> Reçu N° {{ facture.reference }} <h4>
    </div>

    <div style="text-align:center">
        <h4><b> Année scolaire : </b> {{ facture.anneeScolaire }} <h4>
    </div>

    <table class="table table-borderless form-no-mb">
        <thead>
        <tr>
            <th scope="col">Nom et Prénoms</th>
            <th scope="col">Classe</th>
            <th scope="col">Montant payé</th>
            <th scope="col">Total à payer</th>
            <th scope="col">Reste à payer</th>
        </tr>
        </thead>

        <tbody>
        {% for item_form in facture.paiements %}
            {{ component('PaiementLigne', { paiement: item_form }) }}
        {% endfor %}
        <td></td>
        <td></td>
        <td></td>
        <td>{{ facture.totalRemis }} </td>
        <td>{{ facture.montantRestant }} </td>
        </tbody>

        <br>

        <div style="text-align:">
            <h5 style="text-align:right"><b>Mission Tové, le </b> {{ facture.dateFacture |date("d/m/Y") }}  </h5>

        </div>

</div>

templates/components/FactureForm.html.twig
<div {{ attributes }}>

    {{ form_start(form, {
        attr: {
            'data-action': 'live#action:prevent',
            'data-live-action-param': 'save'
        }
    }) }}
    <div class="row">
        <div class="col-4">
            {{ form_row(form.reference, {
                label: false,
                attr: {
                    placeholder: 'Référence de la facture'
                }
            }) }}
        </div>
    </div>

    <table class="table table-borderless form-no-mb">
        <thead>
        <tr>
            <th scope="col">classe</th>
            <th scope="col">inscrit</th>
            <th scope="col">Montant payé</th>
            <th scope="col">Reste à payer</th>
            <th scope="col">Seuil pour une remise paiement unique</th>
            <th scope="col">Montant à verser</th>
            <th scope="col">Actions</th>

        </tr>
        </thead>
        <tbody>
        {% for item_form in form.paiements %}
            <tr>
                <td>{{ form_row(item_form.classe) }}</td>
                <td>{{ form_row(item_form.inscription) }}</td>
                <td>{{ form_row(item_form.montantVerse) }}</td>
                <td>{{ form_row(item_form.montantRestant) }}</td>
                <td>
                    {% if item_form.montantUnique is defined %}
                        {{ form_row(item_form.montantUnique) }}
                    {% endif %}
                </td>
                <td>{{ form_row(item_form.montant) }}</td>
                <td>
                    {{ form_row(item_form.vars.button_delete,
                        {label: 'X', attr:
                            {class: 'btn btn-outline-danger'}
                        }) }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ form_widget(form.paiements.vars.button_add,
        {
            label: '+ Ajouter un élève', attr: {class: 'btn btn-outline-primary'}
        }
    ) }}

    <button type="submit" class="btn btn-success" formnovalidate>Valider</button>
    {{ form_end(form) }}
</div>

templates/components/PaiementLigne.html.twig
<tr {{ attributes }}>
    <td>{{ paiement.inscription.eleve }}</td>
    <td>{{ paiement.inscription.classe }}</td>
    <td>{{ paiement.montant }}</td>
    <td>{{ paiement.inscription.totalRemis }}</td>
    <td>{{ paiement.inscription.montantRestant }}</td>
</tr>

templates/components/RandomNumber.html.twig
<div {{ attributes }}>
    <strong>{{ this.randomNumber }}</strong>

    <button
            data-action="live#$render"
    >Generate a new number!
    </button>
</div>

templates/components/RechercheEleve.html.twig
{# templates/components/ProductSearch.html.twig #}
{# for the Live Component to work, there must be a single root element
    (e.g. a <div>) where the attributes are applied to #}
<div {{ attributes }}>
    <input
            type="search"
            data-model="debounce(100)|query"
    >
    <li data-model="value"> taille eleves recherche {{ value|length }}</li>

    <ul>
        {% for eleve in this.resultats %}
            <li>
                {{ eleve.nom }} {{ eleve.prenoms }}
                <button
                        data-action="live#action"
                        data-live-action-param="addStudent"
                        data-live-id-param="{{ eleve.id }}"
                >Ajouter
                </button>
            </li>

        {% endfor %}
    </ul>
</div>

templates/components/Recu.html.twig
<div style="background-color: white;" {{ attributes }}>
    <div style="text-align:center">
        <h1> COMPLEXE SCOLAIRE ETOILE DE L’EXCELLENCE </h1>
        <h2> Tél : 90 64 67 72 / 92 21 67 69 <h2>
    </div>


    <div style="text-align:right">
        <h4> Reçu N° {{ paiement.facture.reference }} <h4>
    </div>

    <div style="text-align:center">
        <h4><b> Année scolaire : </b> {{ paiement.inscription.classe.anneeScolaire }} <h4>
    </div>

    <div>

        <span style="float: left;"> <b> Reçu de  : </b>  {{ paiement.inscription.eleve }}  </span>
        <span style="float: right;"> <b>Classe : </b>  {{ paiement.inscription.classe }} </span>
    </div>

    <br>

    <div style="text-align:left">
        <h5 style="text-align:left"><b>Montant payé : </b> {{ paiement.montant }} FCFA </h5>

        <h5 style="text-align:left"><b> Pour : </b> Frais de {{ paiement.type }} </h5>
        <h5 style="text-align:left"><b> Total payé : </b> {{ paiement.inscription.totalRemis }} F CFA </h5>
        <h5 style="text-align:left"><b> Reste à payer : </b> {{ paiement.inscription.montantRestant }} F CFA </h5>
    </div>

    <div style="text-align:">
        <h5 style="text-align:right"><b>Mission Tové, le </b> {{ paiement.dateDeTransaction |date("d/m/Y") }}  </h5>

    </div>


</div>